name: Blue-Green Deployment - .NET App to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish --configuration Release --no-build --output ./publish
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bgapp-${{ github.run_number }}
          path: ./publish/
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bgapp-${{ github.run_number }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bg-tdcfloripa2025'
          slot-name: 'staging'
          package: .

      - name: Swap dos slots
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az webapp deployment slot swap \
            --name bg-tdcfloripa2025 \
            --resource-group rg-tdc-floripa-2025 \
            --slot staging \
            --target-slot production
